### ISSUE TITLE
Signup Page

### ISSUE THREAD

**Issue by StanTheMan132** [BalenD/snapshot-project#1]
The sign up route was just completed. We now need to make a frontend signup page. 
It should have a form with method="POST" and action="http://localhost:3000/api/auth/signup". Localhost will we replaced with a ip once we get a server up and running. 
The api expects 2 key's, username and password. Both text values. If you want any other keys added like age or email let me know and ill add it to the backend.

**Comment by BalenD** [comment]
use the issues section to bring up issues, not notify people.
